version: "3.8"

services:
    postgres:
        image: postgres:14
        restart: unless-stopped
        env_file: ./.env
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        network_mode: bridge
        ports:
            - 5432:5432
    app:
        depends_on:
            - postgres
        build: ../ng-teste-backend
        restart: unless-stopped
        env_file: ./.env
        ports:
            - 3333:3333
        volumes:
            - database-data:/var/lib/postgresql/data/
        network_mode: bridge
        links:
            - postgres
        stdin_open: true
        command: ["./wait-for-it.sh", "localhost:5432", "--", "npm", "start"]
        tty: true

volumes:
    database-data:
